version: "3"

services:
  app:
    container_name: N8N-APP
    hostname: N8N-APP
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M   
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_URL}/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

      # Configurações de Monitoramento
      - N8N_METRICS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true

      # Configuração do DB
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=N8N-DB
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}

      # Configuração SMTP
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=outlook.office365.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASS}
      - N8N_SMTP_SENDER=${SMTP_USER}
      - N8N_SMTP_SSL=false
    volumes:
      - N8N-APP-DATA:/home/node/.n8n
      - N8N-APP-DATA-FILES:/files
    networks:
      - N8N-NETWORK-BACK
      - N8N-NETWORK-FRONT
    links:
      - db
    depends_on:
      db:
        condition: service_healthy      

  db:
    container_name: N8N-DB
    hostname: N8N-DB
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}    
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M         
    volumes:
      - N8N-DB-DATA:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - N8N-NETWORK-BACK   

volumes:
  N8N-APP-DATA:
  N8N-APP-DATA-FILES:
  N8N-DB-DATA:

networks:
  N8N-NETWORK-BACK:
  N8N-NETWORK-FRONT:
    driver: bridge
